<a href="https://colab.research.google.com/github/shannon3851/workstuff/blob/main/Rural_potentialdensity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **RURAL POTENTIAL DENSITY**

In [ ]:
import pandas as pd

file_path = '/content/rural_4acresplus.xlsx'
rural_4acresplus = pd.read_excel(file_path)
print(rural_4acresplus.head())

len(rural_4acresplus)

   Join_Count  TARGET_FID  OBJECTID Owner Comment Link  PARCELID  UNIQUE_ID  \
0           1         504       505                        13001      13001
1           2         844       846                        26310      26310
2           1         854       856                        35829      35829
3           1         866       868                        26305      26305
4           2        1945      1949                        18409      18409

  Subdivisio            LocationPr  ...     Tax_Code   Asst__num  \
0                      Blue Shoals  ...  Residential  31687016.0
1             Ely's Peak/Per Ketet  ...  Residential  31684017.0
2                       Greenfield  ...  Residential  30357012.0
3                          Ken-Ely  ...  Residential  31677010.0
4                         Searidge  ...  Residential  90640012.0

              Building_N  Property_D  TRA__sm_ UnitNumber  Shape_Length  \
0            BLUE SHOALS       HOUSE     297.0          1    626.609952
1             Ely's Peak       House     292.0          1    822.166656
2             Greenfield       House     374.0          1    588.243075
3                KEN-ELY       HOUSE     273.0          1    801.454990
4  Sea Ridge - South Apt   Apartment     244.0          1   1206.623338

     Shape_Area Area_Acres  Parish_Name
0  24793.108194   4.366590       Sandys
1  25354.662309   4.465734       Sandys
2  26472.261062   4.659942       Sandys
3  24389.239442   4.295892       Sandys
4  34649.001617   6.105698  Southampton

[5 rows x 36 columns]

34

In [ ]:
# parcels below 4du/acre
rural_4acresplus_count = (rural_4acresplus['Density']<=2)
print(rural_4acresplus_count)

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18    False
19     True
20     True
21    False
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
Name: Density, dtype: bool

In [ ]:
import pandas as pd

file_path = '/content/Res2_forPYTHON.xlsx'
res2 = pd.read_excel(file_path)
print(res2.head())

len(res2)

# Number of parcels below 6du/acre
res2_count = (res2['Density']<6).sum()
print(res2_count)

# % of parcels below 6du/acre
res2percentage = (res2_count / 4631)*100
print(res2percentage)

# Number of parcels above 6du/acre
res2_count2 = (res2['Density']>6).sum()
print(res2_count2)

#% of parcels above 6du/acre
res2percentage2 = (res2_count2 / 4631)*100
print(res2percentage2)

# full distribution
print(res2['Density'].describe())

PARCEL LAYER HAS 3085 ROWS....EXCEL XY TABLE HAS 3485....WHERE ARE THE 400 INPUTS GOING // WHY AREN'T THEY BEING TRANSFERED OVER TO GIS LAYER PROPERLY???

In [33]:
import pandas as pd

#PARCEL LAYER

file_path = '/content/GISlayer_res2_tablejoin_below8du.xls'
below8du = pd.read_excel(file_path)
print(below8du.head(1))

print(len(below8du))

   Parcels_Sept2025.FID  Parcels_Sept2025.OBJECTID Parcels_Sept2025.Owner  \
0                    88                         89

  Parcels_Sept2025.Comment Parcels_Sept2025.Link  Parcels_Sept2025.PARCELID  \
0                                                                     17803

   Parcels_Sept2025.UNIQUE_ID Parcels_Sept2025.Subdivisio  \
0                       17803

  Parcels_Sept2025.LocationPr Parcels_Sept2025.ParishID  ...  \
0                        Lilo                         6  ...

          Sheet1$.Full_Addre  Sheet1$.Units  Sheet1$.Predominat2  \
0  2 Long Point Lane, Sandys            2.0        Residential 2

   Sheet1$.Tax_Code Sheet1$.Asst__num Sheet1$.Building_N Sheet1$.Property_D  \
0       Residential        31473016.0            LI - LO              HOUSE

   Sheet1$.TRA__sm_  Sheet1$.UnitNumber  Sheet1$.ObjectID
0             244.0                 1.0                 1

[1 rows x 74 columns]
3085

In [34]:
# XY TABLE

file_path = '/content/below8du_table_xypoint.xls'
below_xy = pd.read_excel(file_path)
print(below_xy.head(1))

print(len(below_xy))

   OBJECTID Owner Comment Link PARCELID UNIQUE_ID Subdivisio LocationPr  \
0         1                       17803     17803                  Lilo

  ParishID                                Property_N  ...     YCOORD  \
0        6  Lilo, 2 Long Point Road, Cavello Bay, Sy  ...  133088.59

                  Full_Addre  Units    Predominat2     Tax_Code   Asst__num  \
0  2 Long Point Lane, Sandys    2.0  Residential 2  Residential  31473016.0

   Building_N  Property_D  TRA__sm_  UnitNumber
0     LI - LO       HOUSE     244.0         1.0

[1 rows x 33 columns]
3485

In [35]:
print(below8du.describe())

       Parcels_Sept2025.FID  Parcels_Sept2025.OBJECTID  \
count           3085.000000                3085.000000
mean            8385.476823                8393.691086
std             5241.750272                5247.413476
min               88.000000                  89.000000
25%             3521.000000                3526.000000
50%             8004.000000                8009.000000
75%            12532.000000               12542.000000
max            20957.000000               21038.000000

       Parcels_Sept2025.PARCELID  Parcels_Sept2025.UNIQUE_ID  \
count                3085.000000                 3085.000000
mean                28654.265802                28654.265802
std                  8822.203829                 8822.203829
min                  3016.000000                 3016.000000
25%                 21218.000000                21218.000000
50%                 28974.000000                28974.000000
75%                 36366.000000                36366.000000
max                 44810.000000                44810.000000

       Parcels_Sept2025.VacantLot  Parcels_Sept2025.Acreage  \
count                 3085.000000               3085.000000
mean                     0.046029                  0.713672
std                      0.209582                  0.746187
min                      0.000000                  0.125791
25%                      0.000000                  0.353769
50%                      0.000000                  0.517093
75%                      0.000000                  0.804996
max                      1.000000                 11.535200

       Parcels_Sept2025.Area_SqFt  Parcels_Sept2025.Acres  \
count                 3085.000000             3085.000000
mean                 31087.438495                0.713672
std                  32503.784623                0.746187
min                   5479.439941                0.125791
25%                  15410.099609                0.353769
50%                  22524.500000                0.517093
75%                  35065.500000                0.804996
max                 502472.000000               11.535205

       Parcels_Sept2025.Shape_Leng  Parcels_Sept2025.Shape_Area  ...  \
count                  3085.000000                  3085.000000  ...
mean                    275.391301                  4053.460386  ...
std                     145.513568                  4237.675867  ...
min                     106.485197                   714.301617  ...
25%                     193.991763                  2008.611607  ...
50%                     238.143405                  2937.046489  ...
75%                     312.050985                  4572.839065  ...
max                    2053.595857                 65455.264777  ...

       Sheet1$.TARGET_FID  Sheet1$.ADDRESSID  Sheet1$.CIVICNUMBE  \
count         3085.000000        3083.000000         3083.000000
mean          8385.476175       10912.091145           19.361985
std           5241.748755        8514.941557           27.962511
min             88.000000           2.000000            1.000000
25%           3521.000000        4826.500000            5.000000
50%           8004.000000        8897.000000           11.000000
75%          12532.000000       14255.000000           22.000000
max          20957.000000       33725.000000          243.000000

       Sheet1$.XCOORD  Sheet1$.YCOORD  Sheet1$.Units  Sheet1$.Asst__num  \
count     3083.000000     3083.000000    3083.000000       3.075000e+03
mean    547592.941401   132979.647103       1.657476       8.294981e+07
std       4937.381768     3476.789727       1.152304       2.644054e+07
min     537809.050000   127611.860000       1.000000       3.000101e+07
25%     544026.735000   130673.800000       1.000000       7.041062e+07
50%     547844.600000   132652.390000       1.000000       8.127291e+07
75%     551147.365000   135111.270000       2.000000       1.026114e+08
max     558362.340000   142793.000000      19.000000       1.251385e+08

       Sheet1$.TRA__sm_  Sheet1$.UnitNumber  Sheet1$.ObjectID
count       3075.000000              3083.0       3085.000000
mean         266.155447                 1.0       1679.933225
std          164.169250                 0.0        976.158119
min            0.000000                 1.0          1.000000
25%          160.500000                 1.0        843.000000
50%          238.000000                 1.0       1672.000000
75%          331.000000                 1.0       2506.000000
max         2174.000000                 1.0       3485.000000

[8 rows x 42 columns]

In [36]:
below_xy['UNIQUE_ID'].isin(below8du['Parcels_Sept2025.UNIQUE_ID']).value_counts()

UNIQUE_ID
False    3485
Name: count, dtype: int64

In [37]:
below8du['Parcels_Sept2025.UNIQUE_ID'].isin(below_xy['UNIQUE_ID']).value_counts()

Parcels_Sept2025.UNIQUE_ID
False    3085
Name: count, dtype: int64

In [38]:
print(
    below8du.loc[
        below8du['Parcels_Sept2025.UNIQUE_ID'].isin(below_xy['UNIQUE_ID']),
        'Parcels_Sept2025.UNIQUE_ID'
    ]
)

Series([], Name: Parcels_Sept2025.UNIQUE_ID, dtype: int64)

In [40]:
print(below8du['Parcels_Sept2025.UNIQUE_ID'].dtype)
print(below_xy['UNIQUE_ID'].dtype)

int64
object

In [39]:
not_in_layer = below_xy[below_xy['UNIQUE_ID'].isin(below8du['Parcels_Sept2025.UNIQUE_ID'])]
print(not_in_layer)

Empty DataFrame
Columns: [OBJECTID, Owner, Comment, Link, PARCELID, UNIQUE_ID, Subdivisio, LocationPr, ParishID, Property_N, VacantLot, Acreage, Area_SqFt, Predominat, Zoning_Ord, Developmen, Join_Count, Density, TARGET_FID, ADDRESSID, CIVICNUMBE, POSTALCODE, XCOORD, YCOORD, Full_Addre, Units, Predominat2, Tax_Code, Asst__num, Building_N, Property_D, TRA__sm_, UnitNumber]
Index: []

[0 rows x 33 columns]

In [44]:
below_xy[below_xy['UNIQUE_ID'].str.strip().str.isnumeric()]

,OBJECTID,Owner,Comment,Link,PARCELID,UNIQUE_ID,Subdivisio,LocationPr,ParishID,Property_N,...,YCOORD,Full_Addre,Units,Predominat2,Tax_Code,Asst__num,Building_N,Property_D,TRA__sm_,UnitNumber
0,1,,,,17803,17803,,Lilo,6,"Lilo, 2 Long Point Road, Cavello Bay, Sy",...,133088.59,"2 Long Point Lane, Sandys",2.0,Residential 2,Residential,31473016.0,LI - LO,HOUSE,244.0,1.0
1,2,,,,20876,20876,,Palm Creek,5,"Palm Creek, 6 Grasmere Rd, Fairylands, Pm",...,133324.00,"6 Grasmere Road, Pembroke",2.0,Residential 2,Residential,121392015.0,Palm Greek - Upper Apt,Apartment,217.0,1.0
2,3,,,,21768,21768,,Windward,2,,...,132905.00,"21 Tee Street, Devonshire",2.0,Residential 2,Residential,41845013.0,Al Castello,House,527.0,1.0
3,4,,,,40148,40148,,Idolwodd Lagoon Cottage,9,,...,137174.51,"2 Shell Point Road, St. George's",1.0,Residential 2,Residential,50378015.0,IDOLWOOD LAGOON COTTAGE,HOUSE,162.0,1.0
4,5,,,,33714,33714,,Broadreach,5,,...,133551.25,"10 Hallett Crescent, Pembroke",2.0,Residential 2,Residential,121407012.0,MAIN UNIT - BROADREACH,HOUSE,247.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3480,3481,,,,44804,44804,,,5,,...,133545.57,"32 Shaw Wood Road, Pembroke",1.0,Residential 2,Residential,125138512.0,Ballast Cottage,House,246.0,1.0
3481,3482,,Split from 28954 after review of Zoning Order ...,http://www.royalgazette.com/article/20130703/N...,44807,44807,,Gatewood,4,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3482,3483,,,,44809,44809,S3387,,11,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3483,3484,,,,44810,44810,,,4,,...,131428.26,"3 Simons Lane, Paget",1.0,Residential 2,Tourist,71582010.0,Valley Cottages - Tourist,Tourist Apartment,452.0,1.0
3484,3485,,,,29215,29215,,St. Pauls Anglican Church,4,,...,131390.70,"69 Middle Road, Paget",4.0,Residential 2,Commercial,71625119.0,St Pauls Church,Church,0.0,1.0

In [48]:
below_xy['UNIQUE_ID'] = pd.to_numeric(
below_xy['UNIQUE_ID'].str.strip(),
         errors='coerce'
         ).astype('Int64')

In [49]:
print(below_xy['UNIQUE_ID'].isna().sum())

10

In [50]:
print(below8du['Parcels_Sept2025.UNIQUE_ID'].dtype)
print(below_xy['UNIQUE_ID'].dtype)

int64
Int64

In [52]:
not_in_xy = below8du[below8du['Parcels_Sept2025.UNIQUE_ID'].isin(below_xy['UNIQUE_ID'])]
print(not_in_xy)

      Parcels_Sept2025.FID  Parcels_Sept2025.OBJECTID Parcels_Sept2025.Owner  \
0                       88                         89
1                      112                        113
2                      135                        136
3                      192                        193
4                      226                        227
...                    ...                        ...                    ...
3080                 20936                      21011
3081                 20938                      21013
3082                 20947                      21027
3083                 20956                      21037
3084                 20957                      21038

     Parcels_Sept2025.Comment Parcels_Sept2025.Link  \
0
1
2
3
4
...                       ...                   ...
3080
3081
3082
3083
3084

      Parcels_Sept2025.PARCELID  Parcels_Sept2025.UNIQUE_ID  \
0                         17803                       17803
1                         20876                       20876
2                         21768                       21768
3                         40148                       40148
4                         33714                       33714
...                         ...                         ...
3080                      44795                       44795
3081                      20879                       20879
3082                      44804                       44804
3083                      44810                       44810
3084                      29215                       29215

     Parcels_Sept2025.Subdivisio Parcels_Sept2025.LocationPr  \
0                                                       Lilo
1                                                 Palm Creek
2                                                   Windward
3                                    Idolwodd Lagoon Cottage
4                                                 Broadreach
...                          ...                         ...
3080
3081          S3168 and S0019/10                    Highbury
3082
3083
3084                               St. Pauls Anglican Church

     Parcels_Sept2025.ParishID  ...                Sheet1$.Full_Addre  \
0                            6  ...         2 Long Point Lane, Sandys
1                            5  ...         6 Grasmere Road, Pembroke
2                            2  ...         21 Tee Street, Devonshire
3                            9  ...  2 Shell Point Road, St. George's
4                            5  ...     10 Hallett Crescent, Pembroke
...                        ...  ...                               ...
3080                         3  ...       7 Stonehaven Road, Hamilton
3081                         3  ...         5 Old Farm Road, Hamilton
3082                         5  ...       32 Shaw Wood Road, Pembroke
3083                         4  ...              3 Simons Lane, Paget
3084                         4  ...             69 Middle Road, Paget

      Sheet1$.Units  Sheet1$.Predominat2  Sheet1$.Tax_Code Sheet1$.Asst__num  \
0               2.0        Residential 2       Residential        31473016.0
1               2.0        Residential 2       Residential       121392015.0
2               2.0        Residential 2       Residential        41845013.0
3               1.0        Residential 2       Residential        50378015.0
4               2.0        Residential 2       Residential       121407012.0
...             ...                  ...               ...               ...
3080            1.0        Residential 2       Residential        81269315.0
3081            1.0        Residential 2       Residential        81106017.0
3082            1.0        Residential 2       Residential       125138512.0
3083            1.0        Residential 2           Tourist        71582010.0
3084            4.0        Residential 2        Commercial        71625119.0

             Sheet1$.Building_N     Sheet1$.Property_D  Sheet1$.TRA__sm_  \
0                       LI - LO                  HOUSE             244.0
1        Palm Greek - Upper Apt              Apartment             217.0
2                   Al Castello                  House             527.0
3       IDOLWOOD LAGOON COTTAGE                  HOUSE             162.0
4        MAIN UNIT - BROADREACH                  HOUSE             247.0
...                         ...                    ...               ...
3080                        NaN                  House              75.0
3081                   Highbury  House (Uninhabitable)             213.0
3082            Ballast Cottage                  House             246.0
3083  Valley Cottages - Tourist      Tourist Apartment             452.0
3084            St Pauls Church                 Church               0.0

      Sheet1$.UnitNumber  Sheet1$.ObjectID
0                    1.0                 1
1                    1.0                 2
2                    1.0                 3
3                    1.0                 4
4                    1.0                 5
...                  ...               ...
3080                 1.0              3473
3081                 1.0              3475
3082                 1.0              3481
3083                 1.0              3484
3084                 1.0              3485

[3085 rows x 74 columns]

In [53]:
count = (below8du['Parcels_Sept2025.UNIQUE_ID'].isin(below_xy['UNIQUE_ID'])).sum()
print(count)

3085

In [54]:
print(
below8du.loc[
below8du['Parcels_Sept2025.UNIQUE_ID'].isin(below_xy['UNIQUE_ID']),
'Parcels_Sept2025.UNIQUE_ID'
]
)

0       17803
1       20876
2       21768
3       40148
4       33714
        ...
3080    44795
3081    20879
3082    44804
3083    44810
3084    29215
Name: Parcels_Sept2025.UNIQUE_ID, Length: 3085, dtype: int64

In [57]:
missing_mask = below_xy['UNIQUE_ID'].isin(below8du['Parcels_Sept2025.UNIQUE_ID'])

print(missing_mask.sum())

3089

In [55]:
missing_mask = below8du['Parcels_Sept2025.UNIQUE_ID'].isin(below_xy['UNIQUE_ID'])

print(missing_mask.sum())

3085

In [59]:
len(below8du)
len(below_xy)

below8du['Parcels_Sept2025.UNIQUE_ID'].nunique()
below_xy['UNIQUE_ID'].nunique()

below_xy['UNIQUE_ID'].isin(below8du['Parcels_Sept2025.UNIQUE_ID']).value_counts()

UNIQUE_ID
True     3089
False     396
Name: count, dtype: Int64

In [64]:
print(missing['UNIQUE_ID'].isna().sum())
print(missing['UNIQUE_ID'].duplicated().sum())

0
4

In [65]:
print("Rows in below_xy:", len(below_xy))
print("Matched:", below_xy['UNIQUE_ID'].isin(
    below8du['Parcels_Sept2025.UNIQUE_ID']
).sum())
print("Missing:", (~below_xy['UNIQUE_ID'].isin(
    below8du['Parcels_Sept2025.UNIQUE_ID']
)).sum())

Rows in below_xy: 3485
Matched: 3089
Missing: 396

In [72]:
du8below = (below_xy['Density']<=8).sum()
print(du8below)

3485

In [79]:
layer_below8du = (below8du['Sheet1$.Density']<=8).sum()
print(layer_below8du)

3085